### PR TITLE
feat: use stricter linting, fix mistakes

### LINKED ISSUE #252: Switch to `once_cell`
All usages of `lazy_static` in this repository should be replaced by `once_cell`

### PR DESCRIPTION
**Pull request by rvolosatovs**
Closes #252

### CODE REVIEW

File: crates/server/src/auth/tls.rs [hunk 1]
```diff
@@ -19,6 +19,8 @@ use rustls_pemfile::Item::{ECKey, PKCS8Key, RSAKey, X509Certificate};
 pub struct TrustedCertificate;
 
 #[repr(transparent)]
+#[allow(missing_debug_implementations)]
```
Comment (bstrie) [inline crates/server/src/auth/tls.rs:22]: Why?

File: crates/server/src/lib.rs [hunk 2]
```diff
@@ -34,6 +58,7 @@ use log::trace;
 use tokio_util::compat::FuturesAsyncReadCompatExt;
 use tower::MakeService;
 
+#[allow(missing_debug_implementations)] // TlsAcceptor does not implement Debug
```
Comment (bstrie) [inline crates/server/src/lib.rs:61]: A missing Debug impl means that we can't derive Debug, but we can still impl Debug manually. Do you want to do that instead?

File: crates/type/src/digest/digests.rs [hunk 3]
```diff
@@ -157,6 +157,7 @@ where
         &CONTENT_DIGEST
     }
 
+    #[allow(single_use_lifetimes)]
```
Comment (bstrie) [inline crates/type/src/digest/digests.rs:160]: I think this should be unnecessary? Can you remove the `'i` lifetime?

File: crates/type/src/digest/reader.rs [hunk 4]
```diff
@@ -13,6 +13,7 @@ use sha2::digest::DynDigest;
 /// A hashing reader
 ///
 /// This type wraps another reader and hashes the bytes as they are read.
+#[allow(missing_debug_implementations)] // DynDigest does not implement Debug
```
Comment (bstrie) [inline crates/type/src/digest/reader.rs:16]: Same question as above re: manual Debug impl.

File: crates/type/src/digest/verifier.rs [hunk 5]
```diff
@@ -15,6 +15,7 @@ use futures::AsyncRead;
 /// additionally verifies the expected hashes. When the end-of-file condition
 /// is reached, if the actual hashes do not match the expected hashes, an error
 /// is produced.
+#[allow(missing_debug_implementations)] // Reader does not implement Debug
```
Comment (bstrie) [inline crates/type/src/digest/verifier.rs:18]: Same as above.

File: crates/type/src/digest/writer.rs [hunk 6]
```diff
@@ -13,6 +13,7 @@ use sha2::digest::DynDigest;
 /// A hashing writer
 ///
 /// This type wraps another writer and hashes the bytes as they are written.
+#[allow(missing_debug_implementations)] // DynDigest does not implement Debug
```
Comment (bstrie) [inline crates/type/src/digest/writer.rs:16]: Same.

File: crates/type/src/meta.rs [hunk 7]
```diff
@@ -6,6 +6,9 @@ use crate::digest::ContentDigest;
 use mime::Mime;
 use serde::{de::Error as _, Deserialize, Deserializer, Serialize, Serializer};
 
+#[cfg(feature = "http")]
+use http as _;
```
Comment (bstrie) [inline crates/type/src/meta.rs]: What is this for?

File: crates/type/src/repository/config.rs [hunk 8]
```diff
@@ -5,6 +5,7 @@ use serde::{Deserialize, Serialize};
 
 /// A repository config
 #[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
+#[allow(missing_copy_implementations)]
```
Comment (bstrie) [inline crates/type/src/repository/config.rs:8]: Why?

Comment (rvolosatovs) [reply crates/type/src/repository/config.rs:8]: Because we're going to add more fields, which are most probably not going to be `Copy` and removing `Copy` from this struct would be a breaking change

File: crates/server/src/lib.rs (hunk 2 above)
Comment (rvolosatovs) [reply crates/server/src/lib.rs:61]: Not really, because there's no useful information to display.
We can print string `"App"` if you think that's useful

File: crates/type/src/digest/digests.rs (hunk 3 above)
Comment (rvolosatovs) [reply crates/type/src/digest/digests.rs:160]: No, because it's required by the trait

File: crates/type/src/digest/reader.rs (hunk 4 above)
Comment (rvolosatovs) [reply crates/type/src/digest/reader.rs:16]: Why? What would we print?

File: crates/type/src/digest/verifier.rs (hunk 5 above)
Comment (rvolosatovs) [reply crates/type/src/digest/verifier.rs:18]: Same answer

File: crates/type/src/digest/writer.rs (hunk 6 above)
Comment (rvolosatovs) [reply crates/type/src/digest/writer.rs:16]: idem

File: crates/server/src/auth/tls.rs (hunk 1 above)
Comment (bstrie) [reply crates/server/src/auth/tls.rs:22]: Well, the whole point of turning on that lint is that we don't know what consumers of the API might want to debug. If there are secrets, then obviously those shouldn't be printed. But if you disagree with the idea of adding Debug on every public item, then you shouldn't enable that lint in the first place. :P

**Review by bstrie — APPROVED** [review]
